image: node:20

cache: # Cache modules in between jobs
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script:
  - npm run setup:ci

stages:
  - test
  # - test-server
  - lint
  - lint-css
  - build

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - cd client
    - npm ci
    - npm run coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    paths:
      - ./client/coverage/junit.xml
    reports:
      junit: ./client/coverage/junit.xml

# TODO: Fix server tests
# server-test-job:
#   stage: test-server
#   script:
#     - echo "Running unit tests..."
#     - cd server
#     - npm install
#     - npm run test

lint-test-job 1/2:
  stage: lint
  script:
    - echo "Linting code..."
    - npm run lint
    - echo "No lint issues found."

lint-test-job 2/2:
  stage: lint-css
  script:
    - echo "Linting code..."
    - npm run lint:style
    - echo "No lint issues found."

build-client:
  stage: build
  script:
    - echo "Compiling the code..."
    - cd client
    - npm ci
    - npm run build
    - echo "Compile complete."
