image: node:20

cache: # Cache modules in between jobs
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script:
  - npm ci

stages:
  - test
  - lint
  - lint-css
  - build

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - npm run coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    paths:
      - ./coverage/junit.xml
    reports:
      junit: ./coverage/junit.xml

lint-test-job 1/2:
  stage: lint
  script:
    - echo "Linting code..."
    - npm run lint
    - echo "No lint issues found."

lint-test-job 2/2:
  stage: lint-css
  script:
    - echo "Linting code..."
    - npm run lint:style
    - echo "No lint issues found."

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - npm run build:ci
    - echo "Compile complete."
